image: node:latest

before_script:
  - npm i -g firebase-tools

prod-hosting:
  stage: deploy
  environment:
    name: production
    url: https://felixbaker.com
  only:
    - master
  script:
      - yarn
      - yarn build
      - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

